app:
  file:
    path: /Users/a18388871/IdeaProjects/image-storage-service/src/test/resources/tmp
    paging: 100
spring:
  main:
    banner-mode: log
  application:
    name: ImageStorage
  profiles:
    active: PROD



