spring:
  main:
    banner-mode: log
  application:
    name: ImageStorage
  profiles:
    active: PROD
server:
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json,image/jpeg,image/png
    min-response-size: 1024



