spring:
  main:
    banner-mode: log
  application:
    name: ImageStorage
  profiles:
    active: PROD
  resources:
    cache:
      cachecontrol:
        max-age: 300
        must-revalidate: true
server:
  http2:
    enabled: true
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json,image/jpeg,image/png
    min-response-size: 1024



